### PR TITLE
Replace `std::error::Error` with `core::error::Error`

### LINKED ISSUE #81: MSRV: Use core::error::Error instead of std::error::Error
#### Problem

A lot of places in the SDK use the `std` feature to enable an implementation of `std::error::Error`, but this isn't needed because the `Error` trait was moved down to `core.

As mentioned at https://github.com/anza-xyz/solana-sdk/pull/12#discussion_r2002912485 though, using `core::error::Error` instead of `std::error::Error` requires an MSRV bump to 1.81.

#### Proposed Solution

Whenever we want to make an MSRV bump, let's remove the `std::error::Error` usage everywhere in favor of `core::error::Error`. Maybe we can include that whenever we bump the edition to 2024.

### PR DESCRIPTION
**Pull request by divyaranjan1905**
This PR simply replaces instances of `std::error::Error` with `core::error::Error`. It fixes #81, but as mentioned in the issue, it should probably be merged after #115.

Regards,

Divya.

### CODE REVIEW

File: hash/src/lib.rs [hunk 1]
```diff
@@ -95,7 +95,7 @@ pub enum ParseHashError {
 }
 
 #[cfg(feature = "std")]
```
Comment (sonicfromnewyoke) [inline hash/src/lib.rs]: i guess it can be dropped

File: pubkey/src/lib.rs [hunk 2]
```diff
@@ -361,7 +361,7 @@ impl FromPrimitive for ParsePubkeyError {
 }
 
 #[cfg(feature = "std")]
```
Comment (sonicfromnewyoke) [inline pubkey/src/lib.rs]: the same here

File: pubkey/src/lib.rs [hunk 3]
```diff
@@ -103,7 +103,7 @@ impl FromPrimitive for PubkeyError {
...
```
Comment (sonicfromnewyoke) [inline pubkey/src/lib.rs]: and here

File: instruction/src/error.rs [hunk 4]
```diff
@@ -442,7 +442,7 @@ pub enum LamportsError {
 }
 
 #[cfg(feature = "std")]
```
Comment (sonicfromnewyoke) [inline instruction/src/error.rs]: and this one also

File: instruction/src/error.rs [hunk 5]
```diff
@@ -243,7 +243,7 @@ pub enum InstructionError {
...
```
Comment (sonicfromnewyoke) [inline instruction/src/error.rs]: one more place

File: instruction/src/error.rs [hunk 6]
```diff
@@ -243,7 +243,7 @@ pub enum InstructionError {
...
-impl std::error::Error for InstructionError {}
+impl core::error::Error for InstructionError {}
 
 #[cfg(feature = "std")]
```
Comment (sonicfromnewyoke) [inline instruction/src/error.rs]: this is also can be omitted, because this is a `core::fmt::Dispalay` trait

Comment (divyaranjan1905) [reply instruction/src/error.rs]: Okay, I originally considered dropping these attributes, but I wasn't sure. Thank you for confirming.

**Comment by divyaranjan1905** [comment]
Rebased the last few commits and removed the feature attributes for std.

**Comment by joncinque** [comment]
There have been quite a few changes since the PR was first opened, but we should be ready to integrate it -- can you rebase and update your branch? Let me know if you don't have time, and I'll be happy to take this over

**Comment by divyaranjan1905** [comment]
> There have been quite a few changes since the PR was first opened, but we should be ready to integrate it -- can you rebase and update your branch? Let me know if you don't have time, and I'll be happy to take this over

NO worries, will rebase and push by today.

**Comment by kevinheavey** [comment]
Could you please add `rust-version = "1.81.0"` to the Cargo.toml for every crate using `core::error`? 🙏

Otherwise the error messages for people on old Rust versions will be confusing

File: .github/workflows/main.yml [hunk 7]
```diff
@@ -83,24 +83,6 @@ jobs:
       - name: Check formatting
         run: ./scripts/check-fmt.sh
 
-  check:
```
Comment (apfitzge) [inline .github/workflows/main.yml]: why is this PR changing CI?

**Comment by joncinque** [comment]
@divyaranjan1905 do you still have time for this? If not I can take over the PR

**Comment by divyaranjan1905** [comment]
> @divyaranjan1905 do you still have time for this? If not I can take over the PR

I tried to rebase, but it didn't resolve nicely. Anything should I be specifically paying attention to? I'll try once again.

**Comment by joncinque** [comment]
There have been a lot of changes since the PR was created, so it would probably be easier to redo it from scratch. It looks like a few merge commits snuck in too, which probably isn't helping

**Comment by divyaranjan1905** [comment]
@joncinque Would this be required anymore? I was told to remove the `std` attribute from other places, but I am not sure about this.

https://github.com/anza-xyz/solana-sdk/blob/ec56d76d688fcdba3fa59e9cf6cb77f2cf83cace/signature/src/error.rs#L27

File: bls-signatures/src/keypair.rs [hunk 8]
```diff
@@ -120,7 +120,7 @@ impl Keypair {
     pub fn write_json_file<F: AsRef<Path>>(
         &self,
         outfile: F,
-    ) -> Result<String, Box<dyn std::error::Error>> {
+    ) -> Result<String, Box<dyn core::error::Error>> {
```
Comment (joncinque) [inline bls-signatures/src/keypair.rs:123]: Can you add the rust-version to `bls-signatures/Cargo.toml`?

File: quic-definitions/src/lib.rs
Comment (joncinque) [inline quic-definitions/src/lib.rs:1]: Can you add rust-version to `quic-definitions/Cargo.toml`?

File: signature/src/error.rs [hunk 9]
```diff
@@ -12,10 +12,10 @@ use core::fmt::{self, Debug, Display};
 /// (e.g. [BB'06]).
 ///
 /// When the `std` feature is enabled, it impls
-/// [`std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html).
+/// [`core::error::Error`](https://doc.rust-lang.org/nightly/core/error/trait.Error.html).
```
Comment (joncinque) [inline signature/src/error.rs]: nit: No reason to reach for nightly docs here
```suggestion
/// [`core::error::Error`](https://doc.rust-lang.org/core/error/trait.Error.html).
```

File: signature/src/error.rs [hunk 10]
```diff
@@ -12,10 +12,10 @@ use core::fmt::{self, Debug, Display};
...
 ///
 /// When the `alloc` feature is enabled, it supports an optional
-/// [`std::error::Error::source`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source),
+/// [`core::error::Error::source`](https://doc.rust-lang.org/nightly/core/error/trait.Error.html#method.source),
```
Comment (joncinque) [inline signature/src/error.rs]: nit: same here, can just use the stable core docs
```suggestion
/// [`core::error::Error::source`](https://doc.rust-lang.org/core/error/trait.Error.html#method.source),
```

File: signature/src/lib.rs [hunk 11]
```diff
@@ -139,7 +139,6 @@ pub enum ParseSignatureError {
     Invalid,
 }
 
-#[cfg(feature = "std")]
```
Comment (joncinque) [inline signature/src/lib.rs:142]: Be sure to also import `Error` from `core` to go with this change

File: signature/src/error.rs [hunk 12]
```diff
@@ -25,7 +25,7 @@ use core::fmt::{self, Debug, Display};
 pub struct Error {
     /// Source of the error (if applicable).
     #[cfg(all(feature = "std", feature = "alloc"))]
```
Comment (joncinque) [inline signature/src/error.rs]: Can you remove all references to the `std` feature in this file? Now we only need the `alloc` feature

File: signature/src/lib.rs [hunk 13]
```diff
@@ -13,7 +13,8 @@ extern crate alloc;
 #[cfg(feature = "std")]
 extern crate std;
 #[cfg(feature = "std")]
-use std::{error::Error, vec::Vec};
+use core::error::Error;
+use std::vec::Vec;
```
Comment (joncinque) [inline signature/src/lib.rs]: This isn't correct -- the whole point is to only bring in `vec` if the `std` feature is enabled:
```suggestion
#[cfg(feature = "std")]
use std::vec::Vec;
use core::error::Error;
```

File: signature/src/error.rs [hunk 14]
```diff
@@ -1,7 +1,7 @@
 //! Signature error copied directly from
 //! [RustCrypto's opaque signature error](https://github.com/RustCrypto/traits/tree/master/signature)
 
-#[cfg(all(feature = "std", feature = "alloc"))]
+#[cfg(all(feature = "alloc"))]
```
Comment (joncinque) [inline signature/src/error.rs]: nit: for all of these, we don't need `all` anymore
```suggestion
#[cfg(feature = "alloc")]
```

**Comment by divyaranjan1905** [comment]
That should be it :)

Sorry for the tiny mistakes.

**Comment by joncinque** [comment]
Looks like there are some CI failures:

* be sure to run `./cargo nightly fmt --all` to format the code
* check the test errors by running `./scripts/build-sbf.sh` or `./scripts/check-hack.sh`

**Comment by divyaranjan1905** [comment]
Looks like it's still failing. Interesting:
https://github.com/anza-xyz/solana-sdk/actions/runs/16509156545/job/46687480671?pr=116#step:6:659

I have not touched it in my diff though.

**Comment by divyaranjan1905** [comment]
Changing it to `self.source()`, I get the following complaint from the compiler:

```
error[E0599]: the method `as_ref` exists for reference `&&dyn Error`, but its trait bounds were not satisfied  
  --> signature/src/error.rs:85:34  
   |  
85 |             .map(|source| source.as_ref() as &(dyn core::error::Error + 'static))  
   |                                  ^^^^^^  
   |  
   = note: the following trait bounds were not satisfied:  
           `dyn StdError: AsRef<_>`  
           which is required by `&dyn StdError: AsRef<_>`  
           `&dyn StdError: AsRef<_>`  
           which is required by `&&dyn StdError: AsRef<_>`
```

File: signature/src/error.rs [hunk 15]
```diff
@@ -71,18 +71,17 @@ impl Display for Error {
...
 
-#[cfg(feature = "std")]
-impl std::error::Error for Error {
-    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
+impl core::error::Error for Error {
+    fn source(&self) -> Option<&(dyn core::error::Error + 'static)> {
         self.source
             .as_ref()
-            .map(|source| source.as_ref() as &(dyn std::error::Error + 'static))
+            .map(|source| source.as_ref() as &(dyn core::error::Error + 'static))
```
Comment (joncinque) [inline signature/src/error.rs]: The issue is here -- since `source` only exists when the `alloc` feature is enabled, we need to gate this properly:
```suggestion
        #[cfg(feature = "alloc")]
        {
            self.source.as_ref()
            .map(|source| source.as_ref() as &(dyn core::error::Error + 'static))
        }
        #[cfg(not(feature = "alloc"))]
        {
            None
        }
```

**Comment by joncinque** [comment]
Looks like there's still a formatting issue and a build issue. If you can, please run the commands before committing. And if you don't have time, I can take the PR from here

**Comment by divyaranjan1905** [comment]
@joncinque The commands somehow don't run on my system. And it's probably my system's issue. But yeah please take the PR from here and make the necessary formatting fixes.

**Review by apfitzge — APPROVED** [review]
